import React from 'react';

const Disclaimer: React.FC = () => {
  return (
    <div className="max-w-3xl mx-auto bg-slate-100 dark:bg-slate-900 p-8 rounded-lg border border-slate-200 dark:border-slate-800">
      <h2 className="text-3xl font-bold mb-6">Disclaimer & Terms of Use</h2>
      <div className="space-y-4 text-slate-700 dark:text-slate-300 prose dark:prose-invert">
        <p><strong>Last Updated:</strong> {new Date().toLocaleDateString()}</p>
        
        <p>
          Welcome to AI Tattoo Artist. By using this application, you agree to the following terms and conditions.
        </p>

        <h3 className="text-xl font-semibold mt-4">1. For Entertainment & Conceptual Purposes Only</h3>
        <p>
          The images generated by this application are created by an artificial intelligence model. They are intended for entertainment, inspiration, and conceptual visualization only. The results are not a guarantee of what a real tattoo will look like.
        </p>

        <h3 className="text-xl font-semibold mt-4">2. Consult a Professional Artist</h3>
        <p>
          AI-generated designs do not take into account skin type, texture, body contours, or the aging process of a tattoo. Before getting a real tattoo, you MUST consult with a qualified, professional tattoo artist. They can provide expert advice on design, placement, and feasibility. Do not treat the AI output as a final stencil or a substitute for professional artistic guidance.
        </p>
        
        <h3 className="text-xl font-semibold mt-4">3. No Guarantees or Liability</h3>
        <p>
          We make no guarantees regarding the accuracy, quality, or appropriateness of the generated images. We are not liable for any decisions you make based on the output of this application, including but not limited to getting a permanent tattoo. The responsibility for your body art choices is yours alone.
        </p>

        <h3 className="text-xl font-semibold mt-4">4. Image Rights and Usage</h3>
        <p>
          You are responsible for the images you upload. Do not upload content that you do not have the rights to use. While you are free to use the generated images for personal inspiration, be aware that AI-generated art exists in a complex legal landscape.
        </p>

        <p className="mt-6 font-bold">
          By using this app, you acknowledge that you have read, understood, and agree to this disclaimer.
        </p>
      </div>
    </div>
  );
};

export default Disclaimer;