import React from 'react';

const Disclaimer: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto animate-fade-in">
      <div className="bg-white/80 dark:bg-slate-800/80 backdrop-blur-sm p-8 rounded-3xl border border-slate-200/50 dark:border-slate-700/50 shadow-xl">
        <h2 className="text-4xl font-display font-bold mb-8 text-center">
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-ink-600 to-neon-500">
            Disclaimer & Terms of Use
          </span>
        </h2>
        <div className="space-y-6 text-slate-700 dark:text-slate-300 prose dark:prose-invert max-w-none">
          <p className="text-lg font-medium text-ink-600 dark:text-ink-400">
            <strong>Last Updated:</strong> {new Date().toLocaleDateString()}
          </p>
          
          <p className="text-lg leading-relaxed">
            Welcome to InkSync. By using this application, you agree to the following terms and conditions.
          </p>

          <h3 className="text-2xl font-display font-bold mt-8 mb-4 text-slate-900 dark:text-white">1. For Entertainment & Conceptual Purposes Only</h3>
          <p className="text-lg leading-relaxed">
            The images generated by this application are created by an artificial intelligence model. They are intended for entertainment, inspiration, and conceptual visualization only. The results are not a guarantee of what a real tattoo will look like.
          </p>

          <h3 className="text-2xl font-display font-bold mt-8 mb-4 text-slate-900 dark:text-white">2. Consult a Professional Artist</h3>
          <p className="text-lg leading-relaxed">
            AI-generated designs do not take into account skin type, texture, body contours, or the aging process of a tattoo. Before getting a real tattoo, you MUST consult with a qualified, professional tattoo artist. They can provide expert advice on design, placement, and feasibility. Do not treat the AI output as a final stencil or a substitute for professional artistic guidance.
          </p>
          
          <h3 className="text-2xl font-display font-bold mt-8 mb-4 text-slate-900 dark:text-white">3. No Guarantees or Liability</h3>
          <p className="text-lg leading-relaxed">
            We make no guarantees regarding the accuracy, quality, or appropriateness of the generated images. We are not liable for any decisions you make based on the output of this application, including but not limited to getting a permanent tattoo. The responsibility for your body art choices is yours alone.
          </p>

          <h3 className="text-2xl font-display font-bold mt-8 mb-4 text-slate-900 dark:text-white">4. Image Rights and Usage</h3>
          <p className="text-lg leading-relaxed">
            You are responsible for the images you upload. Do not upload content that you do not have the rights to use. While you are free to use the generated images for personal inspiration, be aware that AI-generated art exists in a complex legal landscape.
          </p>

          <div className="mt-8 p-6 bg-ink-50 dark:bg-ink-950/30 rounded-2xl border border-ink-200 dark:border-ink-800">
            <p className="text-lg font-bold text-ink-800 dark:text-ink-200 text-center">
              By using this app, you acknowledge that you have read, understood, and agree to this disclaimer.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Disclaimer;